remote_theme: peterdesmet/petridish

logo: /assets/img/petri-dish_1f9eb.png  # Logo in navbar, will be displayed with 30px height
colors:
  links: "#007bff"                      # Color for links: use a readable color that contrasts well with dark text
  banner: "#63F280"                     # Background color for page banners: use color that contrasts well with white
  footer: "#6c757d"                     # Background color for footer: use color that contrasts well with white
rounded_corners: true                   # Enable (default) rounded corners on boxes and buttons

email: tim.vantilborgh@vub.be
twitter_username: TimVantilborgh
github_username: timvantilborgh

# THEME SETTINGS (ALL OPTIONAL)
posts_on_home: 3                        # Show x number of latest posts on homepage, can be 0
tweets_on_home: true                    # Show Twitter feed of twitter_username on homepage
archive_permalink: /blog/               # Permalink of page using archive.html layout, required when using post categories
